# Generated by Django 5.1.7 on 2025-04-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0003_subadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_two_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('passport_size_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('income_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('annual_income', models.PositiveIntegerField(default=0)),
                ('community_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('nativity_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('transfer_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('conduct_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('physical_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('medical_certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrolix.student')),
            ],
        ),
    ]
