# Generated by Django 5.1.7 on 2025-04-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0005_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='medical_certificate',
            new_name='admit_card',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='fee_reciept',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='migration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='sslc_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
