# Generated by Django 5.1.7 on 2025-04-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0006_rename_medical_certificate_studentapplication_admit_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='migration_certificate',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='type',
            field=models.CharField(default='MERIT', max_length=10),
        ),
    ]
