# Generated by Django 5.1.7 on 2025-04-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0007_remove_studentapplication_migration_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='type',
            field=models.CharField(default='NRI', max_length=10),
        ),
    ]
