# Generated by Django 5.1.7 on 2025-04-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0008_alter_studentapplication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='type',
            field=models.CharField(default='Merit', max_length=10),
        ),
    ]
