# Generated by Django 5.1.7 on 2025-04-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0009_admissionschedule_alter_studentapplication_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionschedule',
            old_name='date',
            new_name='date_of_joining',
        ),
        migrations.RenameField(
            model_name='admissionschedule',
            old_name='time',
            new_name='time_of_joining',
        ),
        migrations.AddField(
            model_name='admissionschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrolix.subadmin'),
        ),
        migrations.AlterField(
            model_name='admissionschedule',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('MECH', 'Mechanical'), ('PRINT', 'Printing Technology'), ('EC', 'Electronics and Computer'), ('EEE', 'Electrical and Electronics'), ('ECE', 'Electronics')], max_length=20, unique=True),
        ),
    ]
