# Generated by Django 5.1.7 on 2025-05-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0011_chatnotification_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrolix.student')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
