# Generated by Django 5.1.7 on 2025-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0013_remove_studentchat_student_chatmessage_subadminreply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionschedule',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='admissionschedule',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science'), ('ece', 'Electronics & Communication'), ('eee', 'Electrical & Electronics'), ('mech', 'Mechanical'), ('civil', 'Printing Technology'), ('EP', 'Computer and Electronics')], max_length=20, unique=True),
        ),
    ]
