# Generated by Django 5.1.7 on 2025-05-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrolix', '0014_remove_admissionschedule_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entrolix.subadmin'),
        ),
        migrations.AlterField(
            model_name='admissionschedule',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('MECH', 'Mechanical'), ('PRINT', 'Printing Technology'), ('EC', 'Electronics and Computer'), ('EEE', 'Electrical and Electronics'), ('ECE', 'Electronics')], max_length=20, unique=True),
        ),
    ]
